baseURL = 'https://jaredhoyt.com/'
languageCode = 'en-us'
title = 'Jared Hoyt'

[module]
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    [[module.imports.mounts]]
      source = "scss"
      target = "assets/stylesheets/plugins/font-awesome"
    [[module.imports.mounts]]
      source = "webfonts"
      target = "static/webfonts"
